name = "GeoExplorer"
uuid = "386f1b4b-9a3d-4ef9-97c4-2a0480d4a57f"
version = "0.1.0"
authors = ["Josh Day <emailjoshday@gmail.com>"]

[deps]
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
OSMGeocoder = "28a637ce-2736-498a-9075-487c6d86a7c1"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Proj = "c94c279d-25a6-4763-9509-64d165bea63e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
TileProviders = "263fe934-28e1-4ae9-998a-c2629c5fede6"
Tyler = "e170d443-b9d6-418a-9ee8-061e966341ef"

[compat]
ColorSchemes = "3.31.0"
Colors = "0.13.1"
Extents = "0.1.6"
GLMakie = "0.13.8"
GeoInterface = "1.6.0"
GeoJSON = "0.8.4"
GeoMakie = "0.7.16"
OSMGeocoder = "0.0.1"
OrderedCollections = "1.8.1"
Printf = "1.11.0"
Proj = "1.9.0"
Reexport = "1.2.2"
Shapefile = "0.13.3"
TileProviders = "0.1.4"
Tyler = "0.2.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
