name = "GeoExplorer"
uuid = "386f1b4b-9a3d-4ef9-97c4-2a0480d4a57f"
authors = ["Josh Day <emailjoshday@gmail.com>"]
version = "0.1.0"

[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
