[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoExplorer = "386f1b4b-9a3d-4ef9-97c4-2a0480d4a57f"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
OSMGeocoder = "28a637ce-2736-498a-9075-487c6d86a7c1"
