[deps]
Extents = "411431e0-e8b7-467b-b5e0-f676ba4f2910"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoExplorer = "386f1b4b-9a3d-4ef9-97c4-2a0480d4a57f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LocalCoverage = "5f6e1e16-694c-5876-87ef-16b5274f298e"
OSMGeocoder = "28a637ce-2736-498a-9075-487c6d86a7c1"
OverpassAPI = "78759bb8-e702-4122-98f4-c2c710342d47"
QuartoNotebookRunner = "4c0109c6-14e9-4c88-93f0-2b974d3468f4"
