[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoExplorer = "386f1b4b-9a3d-4ef9-97c4-2a0480d4a57f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
OSMGeocoder = "28a637ce-2736-498a-9075-487c6d86a7c1"
QuartoNotebookRunner = "4c0109c6-14e9-4c88-93f0-2b974d3468f4"
